app:
    emails-by-minute: 6
    
    
spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/adidas?createDatabaseIfNotExist=true
        username: root
        password: 1111
        driver-class-name: com.mysql.jdbc.Driver
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: group-adidas
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer