app:
    emails-by-minute: 5
    
spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://mysql:3306/adidas?createDatabaseIfNotExist=true
        username: user
        password: 1111
        driver-class-name: com.mysql.jdbc.Driver
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            group-id: group-adidas
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER            
